seq:
	g++ -std=c++17 -g huffman_sequential.cpp -o huffman -Wall

threads:
	g++ -std=c++17 -g huffman_pthread.cpp -o huffman -Wall -pthread

fastflow:
	g++ -std=c++17 -g huffman_fastflow.cpp -o huffman -Wall